### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
trust_remote_code: true
quantization_bit: 4
quantization_method: bitsandbytes

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

### dataset
dataset_dir: ../data
dataset: edu_science_v2_train
eval_dataset: edu_science_v2_dev
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 2

### output
output_dir: ../training/outputs/qwen25-3b-edu-qlora-v2
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.5e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000

### eval
do_eval: true
eval_strategy: steps
eval_steps: 100
per_device_eval_batch_size: 1
